spring:
  application:
    name: whiteboard
  datasource:
    url: jdbc:mariadb://localhost:3306/whiteboard
    username: root
    password: 12345
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
  security:
    user:
      name: admin
      password: admin

mybatis:
  mapper-locations: classpath:mappers/*.xml
